<a href="https://colab.research.google.com/github/tianiachan/TicTacToeUsingRL/blob/main/5B_QLearningusingNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
#source: https://github.com/sayakpaul/FloydHub-Q-Learning-Blog/blob/master/Q-Learning%20using%20numpy.ipynb

# Only numpy
import numpy as np

In [ ]:
# Initialize parameters
gamma = 0.9 # Discount factor 
alpha = 0.75 # Learning rate

In [ ]:
#second run
# Initialize parameters
gamma = 0.5 # Discount factor 
alpha = 0.5 # Learning rate

In [ ]:
#third run
# Initialize parameters
gamma = 0.75 # Discount factor 
alpha = 0.75 # Learning rate

In [ ]:
#fourth run
# Initialize parameters
gamma = 0.3 # Discount factor 
alpha = 0.3 # Learning rate

In [ ]:
# Define the states
location_to_state = {
    'L1' : 0,
    'L2' : 1,
    'L3' : 2,
    'L4' : 3,
    'L5' : 4,
    'L6' : 5,
    'L7' : 6,
    'L8' : 7,
    'L9' : 8
}

# Define the actions
actions = [0,1,2,3,4,5,6,7,8]

# Define the rewards
rewards = np.array([[0,1,0,0,0,0,0,0,0],
              [1,0,1,0,0,0,0,0,0],  #L2 rewards
              [0,1,0,0,0,1,0,0,0],
              [0,0,0,0,0,0,1,0,0],
              [0,1,0,0,0,0,0,1,0], 
              [0,0,1,0,0,0,0,0,0],
              [0,0,0,1,0,0,0,1,0],
              [0,0,0,0,1,0,1,0,1],
              [0,0,0,0,0,0,0,1,0]])
        
# Maps indices to locations
state_to_location = dict((state,location) for location,state in location_to_state.items())




In [ ]:
#change rewards for step 8
rewards = np.array([[0,1,0,0,0,0,0,0,0],
              [1,0,1,0,1,0,0,0,0],
              [0,1,0,0,0,1,0,0,0],
              [0,0,0,0,0,0,1,0,0],
              [0,1,0,0,0,0,0,1,0], 
              [0,0,1,0,0,0,0,0,0],
              [0,0,0,1,0,0,0,1,0],
              [0,0,0,0,1,0,1,0,1],
              [0,0,0,0,0,0,0,1,0]])

In [ ]:
def get_optimal_route(start_location,end_location):
    # Copy the rewards matrix to new Matrix
    rewards_new = np.copy(rewards)
    # Get the ending state corresponding to the ending location as given
    ending_state = location_to_state[end_location]
    # With the above information automatically set the priority of the given ending state to the highest one
    rewards_new[ending_state,ending_state] = 999

    print(rewards_new)

    # -----------Q-Learning algorithm-----------
   
    # Initializing Q-Values
    Q = np.array(np.zeros([9,9]))
    # Q = np.array(np.zeros([10,10])) # for 10 values instead of 9
    # Q-Learning process
    for i in range(1000):
    # for i in range(200):
    # for i in range(50):
        # Pick up a state randomly
        current_state = np.random.randint(0,9) # Python excludes the upper bound
        # current_state = np.random.randint(0,10) # Python excludes the upper bound
        # For traversing through the neighbor locations in the maze
        playable_actions = []
        # Iterate through the new rewards matrix and get the actions > 0
        for j in range(9):
        # for j in range(10):
            if rewards_new[current_state,j] > 0:
                playable_actions.append(j)
        # Pick an action randomly from the list of playable actions leading us to the next state
        next_state = np.random.choice(playable_actions)
        # Compute the temporal difference
        # The action here exactly refers to going to the next state
        TD = rewards_new[current_state,next_state] + gamma * Q[next_state, np.argmax(Q[next_state,])] - Q[current_state,next_state]
        # Update the Q-Value using the Bellman equation
        Q[current_state,next_state] += alpha * TD

    print(Q)
    # Initialize the optimal route with the starting location
    route = [start_location]
    # We do not know about the next location yet, so initialize with the value of starting location
    next_location = start_location
    
    #step counter
    steps = 0
    # We don't know about the exact number of iterations needed to reach to the final location hence while loop will be a good choice for iteratiing
    while(next_location != end_location):
        # Fetch the starting state
        starting_state = location_to_state[start_location]
        # Fetch the highest Q-value pertaining to starting state
        next_state = np.argmax(Q[starting_state,])
        # next_state = np.argmax(Q[2,])
        # print(Q[2])
        # next_state = np.argmax(Q)
        # print(np.argmax(Q))
        # print(Q[starting_state,])
        # print(next_state)
        # We got the index of the next state. But we need the corresponding letter. 
        next_location = state_to_location[next_state]
        # print(next_location)
        route.append(next_location)
        # Update the starting location for the next iteration
        start_location = next_location
        #increment number of steps 
        steps +=1 
    
    return route, steps



In [ ]:
#print results
print(f'Discount Value: {gamma} \nLearning Rate: {alpha}')
print(get_optimal_route('L9', 'L1'))

Discount Value: 0.9 
Learning Rate: 0.75
[[999   1   0   0   0   0   0   0   0]
 [  1   0   1   0   0   0   0   0   0]
 [  0   1   0   0   0   1   0   0   0]
 [  0   0   0   0   0   0   1   0   0]
 [  0   1   0   0   0   0   0   1   0]
 [  0   0   1   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   1   0]
 [  0   0   0   0   1   0   1   0   1]
 [  0   0   0   0   0   0   0   1   0]]
[[9863.09969463 7939.0775531     0.            0.            0.
     0.            0.            0.            0.        ]
 [8863.6292488     0.         7127.9379247     0.            0.
     0.            0.            0.            0.        ]
 [   0.         7939.14278646    0.            0.            0.
  6378.04518848    0.            0.            0.        ]
 [   0.            0.            0.            0.            0.
     0.         5719.95289626    0.            0.        ]
 [   0.         7938.93393969    0.            0.            0.
     0.            0.         6355.16914603    0.  

In [ ]:
#print results -- from l1 to l2
print(f'Discount Value: {gamma} \nLearning Rate: {alpha}')
print(get_optimal_route('L1', 'L2'))


Discount Value: 0.9 
Learning Rate: 0.75
[[  0   1   0   0   0   0   0   0   0]
 [  1 999   1   0   0   0   0   0   0]
 [  0   1   0   0   0   1   0   0   0]
 [  0   0   0   0   0   0   1   0   0]
 [  0   1   0   0   0   0   0   1   0]
 [  0   0   1   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   1   0]
 [  0   0   0   0   1   0   1   0   1]
 [  0   0   0   0   0   0   0   1   0]]
[[   0.         7968.05932743    0.            0.            0.
     0.            0.            0.            0.        ]
 [7108.08762324 8864.16770201 6935.15527541    0.            0.
     0.            0.            0.            0.        ]
 [   0.         7929.99831777    0.            0.            0.
  6286.02725905    0.            0.            0.        ]
 [   0.            0.            0.            0.            0.
     0.         5645.34441451    0.            0.        ]
 [   0.         7868.39023638    0.            0.            0.
     0.            0.         6234.58717188    0.  

In [ ]:
#print results -- from l2to l5
print(f'Discount Value: {gamma} \nLearning Rate: {alpha}')
print(get_optimal_route('L2', 'L5'))
# print(get_optimal_route('L8', 'L5'))

Discount Value: 0.9 
Learning Rate: 0.75
[[  0   1   0   0   0   0   0   0   0]
 [  1   0   1   0   1   0   0   0   0]
 [  0   1   0   0   0   1   0   0   0]
 [  0   0   0   0   0   0   1   0   0]
 [  0   1   0   0 999   0   0   1   0]
 [  0   0   1   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   1   0]
 [  0   0   0   0   1   0   1   0   1]
 [  0   0   0   0   0   0   0   1   0]]
[[   0.         7704.38984495    0.            0.            0.
     0.            0.            0.            0.        ]
 [6919.45608254    0.         6547.49361972    0.         8559.88679009
     0.            0.            0.            0.        ]
 [   0.         7669.65336563    0.            0.            0.
  6208.57747339    0.            0.            0.        ]
 [   0.            0.            0.            0.            0.
     0.         6905.4223685     0.            0.        ]
 [   0.         7520.01866445    0.            0.         9548.29058998
     0.            0.         7626.

In [ ]:
#print results -- from l5 to l8
print(f'Discount Value: {gamma} \nLearning Rate: {alpha}')
print(get_optimal_route('L5', 'L8'))

Discount Value: 0.9 
Learning Rate: 0.75
[[  0   1   0   0   0   0   0   0   0]
 [  1   0   1   0   0   0   0   0   0]
 [  0   1   0   0   0   1   0   0   0]
 [  0   0   0   0   0   0   1   0   0]
 [  0   1   0   0   0   0   0   1   0]
 [  0   0   1   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   1   0]
 [  0   0   0   0   1   0   1 999   1]
 [  0   0   0   0   0   0   0   1   0]]
(['L5', 'L8'], 1)


In [ ]:
#print results -- from l8 to l9
print(f'Discount Value: {gamma} \nLearning Rate: {alpha}')
print(get_optimal_route('L8', 'L9'))

Discount Value: 0.9 
Learning Rate: 0.75
[[  0   1   0   0   0   0   0   0   0]
 [  1   0   1   0   0   0   0   0   0]
 [  0   1   0   0   0   1   0   0   0]
 [  0   0   0   0   0   0   1   0   0]
 [  0   1   0   0   0   0   0   1   0]
 [  0   0   1   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   1   0]
 [  0   0   0   0   1   0   1   0   1]
 [  0   0   0   0   0   0   0   1 999]]
(['L8', 'L9'], 1)


In [10]:
#step 9
# Initialize parameters
gamma = 0.9 # Discount factor 
alpha = 0.75 # Learning rate

In [11]:
# Define the states - to include L10
location_to_state = {
    'L1' : 0,
    'L2' : 1,
    'L3' : 2,
    'L4' : 3,
    'L5' : 4,
    'L6' : 5,
    'L7' : 6,
    'L8' : 7,
    'L9' : 8,
    'L10' : 9
}

# Define the actions
actions = [0,1,2,3,4,5,6,7,8,9]

# Define the rewards
rewards = np.array([[0,1,0,0,0,0,0,0,0,0], #l1
              [1,0,1,0,0,0,0,0,0,0], #l2
              [0,1,0,0,0,1,0,0,0,0], #l3
              [0,0,0,0,0,0,1,0,0,0], #l4
              [0,1,0,0,0,0,0,1,0,0], #l5
              [0,0,1,0,0,0,0,0,0,0], #l6
              [0,0,0,1,0,0,0,1,0,0], #l7
              [0,0,0,0,1,0,1,0,1,0], #l8
              [0,0,0,0,0,0,0,1,0,1], #l9
              [0,0,0,0,0,0,0,0,1,0]]) #l10
        
# Maps indices to locations
state_to_location = dict((state,location) for location,state in location_to_state.items())

In [12]:
def get_optimal_route(start_location,end_location):
    # Copy the rewards matrix to new Matrix
    rewards_new = np.copy(rewards)
    # Get the ending state corresponding to the ending location as given
    ending_state = location_to_state[end_location]
    # With the above information automatically set the priority of the given ending state to the highest one
    rewards_new[ending_state,ending_state] = 999

    print(rewards_new)

    # -----------Q-Learning algorithm-----------
   
    # Initializing Q-Values
    # Q = np.array(np.zeros([9,9]))
    Q = np.array(np.zeros([10,10])) # for 10 values instead of 9
    # Q-Learning process
    for i in range(1000):
    # for i in range(200):
    # for i in range(50):
        # Pick up a state randomly
        # current_state = np.random.randint(0,9) # Python excludes the upper bound
        current_state = np.random.randint(0,10) # Python excludes the upper bound
        # For traversing through the neighbor locations in the maze
        playable_actions = []
        # Iterate through the new rewards matrix and get the actions > 0
        # for j in range(9):
        for j in range(10):
            if rewards_new[current_state,j] > 0:
                playable_actions.append(j)
        # Pick an action randomly from the list of playable actions leading us to the next state
        next_state = np.random.choice(playable_actions)
        # Compute the temporal difference
        # The action here exactly refers to going to the next state
        TD = rewards_new[current_state,next_state] + gamma * Q[next_state, np.argmax(Q[next_state,])] - Q[current_state,next_state]
        # Update the Q-Value using the Bellman equation
        Q[current_state,next_state] += alpha * TD

    # Initialize the optimal route with the starting location
    route = [start_location]
    # We do not know about the next location yet, so initialize with the value of starting location
    next_location = start_location
    
    #step counter
    steps = 0
    # We don't know about the exact number of iterations needed to reach to the final location hence while loop will be a good choice for iteratiing
    while(next_location != end_location):
        # Fetch the starting state
        starting_state = location_to_state[start_location]
        # Fetch the highest Q-value pertaining to starting state
        next_state = np.argmax(Q[starting_state,])
        # We got the index of the next state. But we need the corresponding letter. 
        next_location = state_to_location[next_state]
        route.append(next_location)
        # Update the starting location for the next iteration
        start_location = next_location
        #increment number of steps 
        steps +=1 
    
    return route, steps

In [13]:
#print results  -- default to make sure changes all work
print(f'Discount Value: {gamma} \nLearning Rate: {alpha}')
print(get_optimal_route('L9', 'L1'))

Discount Value: 0.9 
Learning Rate: 0.75
[[999   1   0   0   0   0   0   0   0   0]
 [  1   0   1   0   0   0   0   0   0   0]
 [  0   1   0   0   0   1   0   0   0   0]
 [  0   0   0   0   0   0   1   0   0   0]
 [  0   1   0   0   0   0   0   1   0   0]
 [  0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   1   0   0]
 [  0   0   0   0   1   0   1   0   1   0]
 [  0   0   0   0   0   0   0   1   0   1]
 [  0   0   0   0   0   0   0   0   1   0]]
(['L9', 'L8', 'L5', 'L2', 'L1'], 4)


In [14]:
#print results
print(f'Discount Value: {gamma} \nLearning Rate: {alpha}')
print(get_optimal_route('L10', 'L1'))

Discount Value: 0.9 
Learning Rate: 0.75
[[999   1   0   0   0   0   0   0   0   0]
 [  1   0   1   0   0   0   0   0   0   0]
 [  0   1   0   0   0   1   0   0   0   0]
 [  0   0   0   0   0   0   1   0   0   0]
 [  0   1   0   0   0   0   0   1   0   0]
 [  0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   1   0   0]
 [  0   0   0   0   1   0   1   0   1   0]
 [  0   0   0   0   0   0   0   1   0   1]
 [  0   0   0   0   0   0   0   0   1   0]]
(['L10', 'L9', 'L8', 'L5', 'L2', 'L1'], 5)


In [16]:
#print results
print(f'Discount Value: {gamma} \nLearning Rate: {alpha}')
print(get_optimal_route('L10', 'L4'))

Discount Value: 0.9 
Learning Rate: 0.75
[[  0   1   0   0   0   0   0   0   0   0]
 [  1   0   1   0   0   0   0   0   0   0]
 [  0   1   0   0   0   1   0   0   0   0]
 [  0   0   0 999   0   0   1   0   0   0]
 [  0   1   0   0   0   0   0   1   0   0]
 [  0   0   1   0   0   0   0   0   0   0]
 [  0   0   0   1   0   0   0   1   0   0]
 [  0   0   0   0   1   0   1   0   1   0]
 [  0   0   0   0   0   0   0   1   0   1]
 [  0   0   0   0   0   0   0   0   1   0]]
(['L10', 'L9', 'L8', 'L7', 'L4'], 4)
